# CMake generated Testfile for 
# Source directory: C:/oss/third_party/sundials/sundials-3.1.0/examples/sunmatrix/sparse
# Build directory: C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_400_400_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_400_400_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Debug/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"400 400 0 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_400_400_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_400_400_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Release/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"400 400 0 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_400_400_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_400_400_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/MinSizeRel/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"400 400 0 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_400_400_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_400_400_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/RelWithDebInfo/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"400 400 0 0\"")
else()
  add_test(test_sunmatrix_sparse_400_400_0_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_450_450_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_450_450_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Debug/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"450 450 1 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_450_450_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_450_450_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Release/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"450 450 1 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_450_450_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_450_450_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/MinSizeRel/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"450 450 1 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_450_450_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_450_450_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/RelWithDebInfo/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"450 450 1 0\"")
else()
  add_test(test_sunmatrix_sparse_450_450_1_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_200_1000_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_200_1000_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Debug/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"200 1000 0 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_200_1000_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_200_1000_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Release/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"200 1000 0 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_200_1000_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_200_1000_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/MinSizeRel/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"200 1000 0 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_200_1000_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_200_1000_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/RelWithDebInfo/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"200 1000 0 0\"")
else()
  add_test(test_sunmatrix_sparse_200_1000_0_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_6000_350_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_6000_350_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Debug/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"6000 350 0 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_6000_350_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_6000_350_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Release/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"6000 350 0 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_6000_350_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_6000_350_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/MinSizeRel/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"6000 350 0 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_6000_350_0_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_6000_350_0_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/RelWithDebInfo/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"6000 350 0 0\"")
else()
  add_test(test_sunmatrix_sparse_6000_350_0_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_500_5000_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_500_5000_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Debug/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"500 5000 1 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_500_5000_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_500_5000_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Release/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"500 5000 1 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_500_5000_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_500_5000_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/MinSizeRel/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"500 5000 1 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_500_5000_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_500_5000_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/RelWithDebInfo/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"500 5000 1 0\"")
else()
  add_test(test_sunmatrix_sparse_500_5000_1_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunmatrix_sparse_4000_800_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_4000_800_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Debug/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"4000 800 1 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunmatrix_sparse_4000_800_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_4000_800_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/Release/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"4000 800 1 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunmatrix_sparse_4000_800_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_4000_800_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/MinSizeRel/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"4000 800 1 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunmatrix_sparse_4000_800_1_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_4000_800_1_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/RelWithDebInfo/test_sunmatrix_sparse.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"4000 800 1 0\"")
else()
  add_test(test_sunmatrix_sparse_4000_800_1_0 NOT_AVAILABLE)
endif()
