# CMake generated Testfile for 
# Source directory: C:/oss/third_party/sundials/sundials-3.1.0/examples/sunlinsol/band
# Build directory: C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunlinsol_band_10_2_3_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_10_2_3_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/Debug/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"10 2 3 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunlinsol_band_10_2_3_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_10_2_3_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/Release/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"10 2 3 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunlinsol_band_10_2_3_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_10_2_3_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/MinSizeRel/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"10 2 3 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunlinsol_band_10_2_3_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_10_2_3_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/RelWithDebInfo/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"10 2 3 0\"")
else()
  add_test(test_sunlinsol_band_10_2_3_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunlinsol_band_300_7_4_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_300_7_4_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/Debug/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"300 7 4 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunlinsol_band_300_7_4_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_300_7_4_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/Release/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"300 7 4 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunlinsol_band_300_7_4_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_300_7_4_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/MinSizeRel/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"300 7 4 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunlinsol_band_300_7_4_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_300_7_4_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/RelWithDebInfo/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"300 7 4 0\"")
else()
  add_test(test_sunlinsol_band_300_7_4_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunlinsol_band_1000_8_8_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_1000_8_8_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/Debug/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"1000 8 8 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunlinsol_band_1000_8_8_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_1000_8_8_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/Release/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"1000 8 8 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunlinsol_band_1000_8_8_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_1000_8_8_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/MinSizeRel/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"1000 8 8 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunlinsol_band_1000_8_8_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_1000_8_8_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/RelWithDebInfo/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"1000 8 8 0\"")
else()
  add_test(test_sunlinsol_band_1000_8_8_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sunlinsol_band_5000_3_100_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_5000_3_100_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/Debug/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"5000 3 100 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sunlinsol_band_5000_3_100_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_5000_3_100_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/Release/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"5000 3 100 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sunlinsol_band_5000_3_100_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_5000_3_100_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/MinSizeRel/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"5000 3 100 0\"")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sunlinsol_band_5000_3_100_0 "C:/Python36/python.exe" "C:/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_5000_3_100_0" "--executablename=C:/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/RelWithDebInfo/test_sunlinsol_band.exe" "--outputdir=C:/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"5000 3 100 0\"")
else()
  add_test(test_sunlinsol_band_5000_3_100_0 NOT_AVAILABLE)
endif()
